<?php

/**

 * The Header template for our theme

 *

 * Displays all of the <head> section and everything up till <div id="main">

 *

 * @package WordPress

 * @subpackage Twenty_Thirteen

 * @since Twenty Thirteen 1.0

 */

?><!DOCTYPE html>
<!-- tso test -->

<!--[if IE 7]>

<html class="ie ie7" <?php language_attributes(); ?>>

<![endif]-->

<!--[if IE 8]>

<html class="ie ie8" <?php language_attributes(); ?>>

<![endif]-->

<!--[if !(IE 7) & !(IE 8)]><!-->

<html <?php language_attributes(); ?>>

<!--<![endif]-->

<head>

	<meta charset="<?php bloginfo( 'charset' ); ?>">

	<meta name="viewport" content="width=device-width">

	<title><?php wp_title( '|', true, 'right' ); ?></title>

	<link rel="profile" href="http://gmpg.org/xfn/11">

	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">

	<!--[if lt IE 9]>

	<script src="<?php echo get_template_directory_uri(); ?>/js/html5.js"></script>

	<![endif]-->
	
	<style>
	
		/* Critical Path CSS Generated by Pegasaas Accelerator at https://pegasaas.com/ for https://chemicaltranslator.com/ */
@font-face{font-family: 'Roboto';font-style: italic;font-weight: 400;font-display: swap;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOkCnqEu92Fr1Mu51xIIzc.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 400;font-display: swap;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxP.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 700;font-display: swap;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmWUlfBBc9.ttf) format('truetype')}@charset "UTF-8";h1,h2,h3{overflow-wrap: break-word}ul{overflow-wrap: break-word}p{overflow-wrap: break-word}:root{--wp--preset--font-size--normal: 16px;--wp--preset--font-size--huge: 42px}.screen-reader-text{border: 0;clip: rect(1px,1px,1px,1px);-webkit-clip-path: inset(50%);clip-path: inset(50%);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;word-wrap: normal!important}.hamburger{padding: 15px 15px;display: inline-block;font: inherit;color: inherit;text-transform: none;background-color: transparent;border: 0;margin: 0;overflow: visible}.hamburger-box{width: 30px;height: 24px;display: inline-block;position: relative}.hamburger-inner{display: block;top: 50%;margin-top: -2px}.hamburger-inner,.hamburger-inner::after,.hamburger-inner::before{width: 30px;height: 4px;background-color: #000;border-radius: 4px;position: absolute}.hamburger-inner::after,.hamburger-inner::before{content: "";display: block}.hamburger-inner::before{top: -10px}.hamburger-inner::after{bottom: -10px}.hamburger--slider .hamburger-inner{top: 2px}.hamburger--slider .hamburger-inner::before{top: 10px}.hamburger--slider .hamburger-inner::after{top: 20px}@font-face{font-family: wprmenu;src: url(https://chemicaltranslator.com/wp-content/plugins/wp-responsive-menu/assets/fonts/wprmenu.eot?p8o4s0);src: url(https://chemicaltranslator.com/wp-content/plugins/wp-responsive-menu/assets/fonts/wprmenu.eot?p8o4s0#iefix) format('embedded-opentype'),url(https://chemicaltranslator.com/wp-content/plugins/wp-responsive-menu/assets/fonts/wprmenu.ttf?p8o4s0) format('truetype'),url(https://chemicaltranslator.com/wp-content/plugins/wp-responsive-menu/assets/fonts/wprmenu.woff?p8o4s0) format('woff'),url(https://chemicaltranslator.com/wp-content/plugins/wp-responsive-menu/assets/fonts/wprmenu.svg?p8o4s0#wprmenu) format('svg');font-weight: 400;font-style: normal}#wprmenu_bar,#wprmenu_bar *{margin: 0;padding: 0;-moz-box-sizing: border-box!important;-webkit-box-sizing: border-box!important;box-sizing: border-box!important;font-family: inherit;text-align: left;font-size: 100%;font-weight: 400}html body div.wprm-wrapper{z-index: 999999}#wprmenu_bar{position: fixed;background: #4c656c;padding: 10px 16px;overflow: hidden;height: 42px;z-index: 99999}#wprmenu_bar .menu_title{font-weight: 400;font-size: 20px;line-height: 35px;position: relative;top: -6px}#wprmenu_bar .menu_title a{display: inline-block;position: relative;top: 4px}#wprmenu_bar div.hamburger{margin-top: -3px}body{position: relative!important}#wprmenu_menu_ul .sub-menu{padding: 0}#mg-wprm-wrap ul li{margin: 0}#mg-wprm-wrap ul li ul.sub-menu li{border: none;position: relative}html body #wprmenu_menu_ul li.wprmenu_parent_item_li>ul{margin-left: 0!important}div#mg-wprm-wrap ul li span.wprmenu_icon{font-family: wprmenu;position: absolute;right: 10px;line-height: 38px;padding: 24px}div#mg-wprm-wrap ul#wprmenu_menu_ul>li>span.wprmenu_icon:before{right: 3px}div#mg-wprm-wrap ul li span.wprmenu_icon:before{top: 3px}html body #wprmenu_menu_ul li.wprmenu_parent_item_li>ul{padding: 0 10px;margin: 0}#mg-wprm-wrap{z-index: 9999}#mg-wprm-wrap ul li a{text-decoration: none;z-index: 9999}.icon_default.wprmenu_icon_par:before{content: "\74";position: absolute}.wprmenu_icon{position: relative;-webkit-transform: rotate(0);-moz-transform: rotate(0);-o-transform: rotate(0);transform: rotate(0);float: left}span.wprmenu_icon.wprmenu_icon_par{top: 4px}#mg-wprm-wrap li.menu-item-has-children{position: relative}#wprmenu_menu_ul{padding: 0 0 50px;margin: 0;overflow: hidden}#wprmenu_menu_ul ul.sub-menu{margin-left: 0}#mg-wprm-wrap li.menu-item a{padding: 13px 14px}.cbp-spmenu{position: fixed;overflow: auto;height: 100%;z-index: 9999}.cbp-spmenu a{padding: 1em;display: block}#mg-wprm-wrap.cbp-spmenu-left{top: 42px}.cbp-spmenu-left{left: -100%}.cbp-spmenu-push{overflow-x: hidden;position: relative}#mg-wprm-wrap,#wprmenu_bar{display: none}#wprmenu_bar{top: 0}#wprmenu_bar,.cbp-spmenu-push{left: 0}#wprmenu_bar,html body div.wprm-wrapper{width: 100%}#wprmenu_bar,#wprmenu_bar *,#wprmenu_menu_ul,#wprmenu_menu_ul .sub-menu{list-style: none}.wpml-ls-menu-item .wpml-ls-flag{display: inline;vertical-align: baseline}*{-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box}article,aside,footer,header,nav,section{display: block}@media only screen and (device-width:768px) and (orientation:portrait){body{width: 768px}}@media only screen and (device-width:768px) and (orientation:landscape){body{width: 1024px}}html{font-size: 100%;overflow-y: scroll;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%}button,html,textarea{font-family: Roboto,sans-serif}body{color: #5b687d;line-height: 1.5;margin: 0;background: #f2f2f2;font-family: Roboto,sans-serif;-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale}a{color: #ca3c08;text-decoration: none}a:visited{color: #ac0404}h1,h2,h3{clear: both;font-family: Roboto,sans-serif;line-height: 1.3;font-weight: 400;-webkit-font-smoothing: antialiased;-webkit-font-smoothing: antialiased;-ms-font-smoothing: antialiased;-o-font-smoothing: antialiased}h1{font-size: 30px;margin: 33px 0}h2{font-size: 30px;margin: 25px 0}h3{font-size: 22px;margin: 22px 0}p{margin: 0 0 24px}ul{margin: 16px 0;padding: 0 0 0 40px}ul{list-style-type: square}nav ul{list-style: none;list-style-image: none}li>ul{margin: 0}img{-ms-interpolation-mode: bicubic;border: 0;vertical-align: middle}button,textarea{font-size: 100%;margin: 0;max-width: 100%;vertical-align: baseline}button{line-height: normal}button{-webkit-appearance: button}button::-moz-focus-inner{border: 0;padding: 0}textarea{overflow: auto;vertical-align: top}.menu-toggle:after{-webkit-font-smoothing: antialiased;display: inline-block;font: normal 16px/1 Genericons;vertical-align: text-bottom}.entry-content:after,.navigation:after,.site-footer .widget-area:after{clear: both}.entry-content:after,.entry-content:before,.navigation:after,.navigation:before,.site-footer .widget-area:after,.site-footer .widget-area:before{content: "";display: table}.screen-reader-text{clip: rect(1px,1px,1px,1px);position: absolute!important}button,textarea{border: 2px solid #d4d0ba;font-family: Raleway,sans-serif;padding: 5px}textarea{color: #141412}button{background: #e05d22;background: -webkit-linear-gradient(top,#e05d22 0,#d94412 100%);background: linear-gradient(to bottom,#e05d22 0,#d94412 100%);border: none;border-bottom: 3px solid #b93207;border-radius: 2px;color: #fff;display: inline-block;padding: 11px 24px 10px;text-decoration: none}::-webkit-input-placeholder{color: #7d7b6d}:-moz-placeholder{color: #7d7b6d}::-moz-placeholder{color: #7d7b6d}:-ms-input-placeholder{color: #7d7b6d}.entry-content img{max-width: 100%}.entry-content img,img[class*=attachment-]{height: auto}img.size-full,img.size-large{height: auto;max-width: 100%}iframe{max-width: 100%}.site{border-left: 1px solid #f2f2f2;border-right: 1px solid #f2f2f2;margin: 0 auto;width: 100%}.site-main{position: relative;max-width: 1080px;margin: 0 auto;padding: 0 20px}.site-header{position: relative}.site-header .home-link{color: #141412;display: block;margin: 0 auto;max-width: 1080px;padding: 0 20px;text-decoration: none;width: 100%}.site-title{font-size: 60px;font-weight: 700;line-height: 1;margin: 0;padding: 10px 0 0}.main-navigation{clear: both;margin: 0 auto;max-width: 1080px;min-height: 45px;position: relative}ul.nav-menu{margin: 0;float: right;display: flex}.nav-menu li{border-right: thin solid #19417e;display: inline-block;position: relative}.nav-menu li:last-child{border: none}.nav-menu li a{color: #141412;display: block;font-size: 16px;line-height: 1;padding: 15px 20px;text-decoration: none}.current_page_item{background-color: #01b1aa;color: #fff}.nav-menu .sub-menu{background-color: #220e10;border: 2px solid #f7f5e7;border-top: 0;padding: 0;position: absolute;left: -2px;z-index: 99999;height: 1px;width: 1px;overflow: hidden;clip: rect(1px,1px,1px,1px)}ul.nav-menu ul a{color: #fff;margin: 0;width: 200px}.nav-menu .current-menu-item>a,.nav-menu .current_page_item>a{color: #000}.menu-toggle{display: none}.navbar{margin: 0 auto;max-width: 1600px;width: 100%;float: left}.entry-content,.entry-header,.entry-meta{margin: 0 auto;width: 100%}.entry-header{margin-bottom: 30px}.entry-meta{clear: both;font-size: 14px}.entry-content{-webkit-hyphens: auto;-moz-hyphens: auto;-ms-hyphens: auto;hyphens: auto;word-wrap: break-word;float: left;width: 65.3%;padding: 15px!important}.entry-content a{color: #bc360a}footer.entry-meta{margin-top: 24px}.navigation a{color: #bc360a}.widget{font-size: 14px;-webkit-hyphens: auto;-moz-hyphens: auto;-ms-hyphens: auto;hyphens: auto;margin: 0 0 24px;word-wrap: break-word}.widget .widget-title{margin: 0 0 10px;font-weight: 400}.widget ul{list-style-type: none;margin: 0;padding: 0}.widget li{padding: 5px 0}.widget a{color: #18407e}.site-footer{background-color: #0378ac;color: #686758;font-size: 14px;text-align: center;float: left;width: 100%;margin-top: 0!important}.site-footer .widget-area{text-align: left}.site-footer a{color: #686758}.site-footer .sidebar-container{background-color: #0378ac;padding: 20px 0}.site-footer .widget-area{margin: 0 auto;max-width: 1040px;width: 100%}.site-footer .widget{background: 0 0;color: #fff;float: left;margin-right: 20px;width: 32%;margin-bottom: 0;padding: 20px 0 20px 0}.site-footer .widget:last-child{float: right!important;margin-right: 0!important}.site-footer .widget p{margin-bottom: 10px}.site-footer .widget a{color: #e6402a}.site-footer .widget-title{color: #fff}.logo{float: left;width: 29%}.top-right{float: right;width: 69%}.top-links{float: left;width: 100%;margin-top: 10px}.top-links ul{float: right;width: 83%}.top-links li{float: left;list-style: none;margin-right: .5%}.top-links .email{background: url("https://chemicaltranslator.com/wp-content/themes/chemical-translator/images/email-bg.png") no-repeat scroll 0 7px rgba(0,0,0,0);padding-left: 25px;margin-right: 7px}.top-links .email a{color: #141412}.banner{border-top: 5px solid #18407e;float: left;margin-top: 5px;width: 100%}.main-content{float: left;width: 100%;background: #fff}.content-area{max-width: 1040px;padding: 0;margin: 0 auto}.copy-right{color: #fff;float: left;padding: 10px 20px 0 20px;width: 100%}.copy-right .footer-left{float: left;width: 85%}.copy-right .footer-right{float: right;width: 13%}.copy-right .footer-right ul{float: right;padding: 0;width: 100%;margin: 0}.copy-right .footer-right li{list-style: none;float: left;margin-right: 3%;position: relative}.copy-right .footer-right li img{opacity: .8;position: relative;margin-bottom: 0}@-ms-viewport{width: device-width}@viewport{width: device-width}@media (max-width:1599px){.site{border: 0}}@media (max-width:1024px){.site-footer .widget-area{padding-left: 20px;padding-right: 20px}}@media screen and (max-width:800px){.navbar{display: none}.site-header{margin-top: 43px}.top-links .email{width: 63%}.content-area{max-width: 800px}.site-footer .widget{width: 31%}.copy-right .footer-right{width: 17%}}@media (max-width:768px){.site-header .home-link{min-height: 0}.site-title{font-size: 36px;padding: 8px 0 10px}.top-links .email{width: 100%;margin-bottom: 2%}.site-footer .widget{width: 46%;height: 250px}.copy-right .footer-right{width: 22%}}@media (max-width:643px){.site-title{font-size: 30px}#content .entry-content,#content .entry-header,#content footer.entry-meta{padding-left: 20px;padding-right: 20px}.menu-toggle{display: inline-block;font: bold 16px/1.3 "Source Sans Pro",Helvetica,sans-serif;margin: 0}.menu-toggle{background: 0 0;border: none;color: #141412;padding: 12px 0 12px 20px}.menu-toggle:after{content: "\f502";font-size: 12px;padding-left: 8px;vertical-align: -4px}ul.nav-menu{display: none}.copy-right .footer-left{float: left;margin-bottom: 10px;text-align: center;width: 100%}.copy-right .footer-right{text-align: center;width: 100%}.copy-right .footer-right ul{width: 65%}}@media (max-width:480px){.logo{width: 100%;text-align: center}.top-right{width: 100%}.site-footer .widget{width: 100%}.site-footer .widget{height: auto!important}.entry-content{width: 100%!important}}@media (max-width:359px){.site-title{font-weight: 400}.top-links ul{width: 100%}.site-footer .widget{height: auto}}h3{color: #14b6b1!important}.site-footer a{color: #fff!important}.site-footer .menu-item{border-bottom: solid 1px #fff}.page-template-ac-single-col .entry-content{width: 100%!important;padding: 0!important}.u-dn{display: none!important}@media screen and (max-width:400px){.u-mob-pr0 .elementor-widget-container{padding-right: 0!important}.u-mob-mr0 .elementor-widget-container{margin-right: 0!important}}@media screen and (max-width:400px){.u-mob-pl0 .elementor-widget-container{padding-left: 0!important}.u-mob-ml0 .elementor-widget-container{margin-left: 0!important}}.main-navigation a{height: 100%}@font-face{font-family: Genericons;src: url('https://chemicaltranslator.com/wp-content/themes/chemical-translator/genericons/font/genericons-regular-webfont.eot')}.elementor-column-gap-default>.elementor-row>.elementor-column>.elementor-element-populated>.elementor-widget-wrap{padding: 10px}@media (max-width:767px){.elementor-column{width: 100%}}.screen-reader-text{position: absolute;top: -10000em;width: 1px;height: 1px;margin: -1px;padding: 0;overflow: hidden;clip: rect(0,0,0,0);border: 0}.elementor-clearfix:after{content: "";display: block;clear: both;width: 0;height: 0}.elementor{-webkit-hyphens: manual;-ms-hyphens: manual;hyphens: manual}.elementor *,.elementor :after,.elementor :before{-webkit-box-sizing: border-box;box-sizing: border-box}.elementor a{-webkit-box-shadow: none;box-shadow: none;text-decoration: none}.elementor img{height: auto;max-width: 100%;border: none;border-radius: 0;-webkit-box-shadow: none;box-shadow: none}.elementor-element{--flex-direction: initial;--flex-wrap: initial;--justify-content: initial;--align-items: initial;--align-content: initial;--gap: initial;--flex-basis: initial;--flex-grow: initial;--flex-shrink: initial;--order: initial;--align-self: initial;-webkit-box-orient: vertical;-webkit-box-direction: normal;-ms-flex-direction: var(--flex-direction);flex-direction: var(--flex-direction);-ms-flex-wrap: var(--flex-wrap);flex-wrap: var(--flex-wrap);-webkit-box-pack: var(--justify-content);-ms-flex-pack: var(--justify-content);justify-content: var(--justify-content);-webkit-box-align: var(--align-items);-ms-flex-align: var(--align-items);align-items: var(--align-items);-ms-flex-line-pack: var(--align-content);align-content: var(--align-content);gap: var(--gap);-ms-flex-preferred-size: var(--flex-basis);flex-basis: var(--flex-basis);-webkit-box-flex: var(--flex-grow);-ms-flex-positive: var(--flex-grow);flex-grow: var(--flex-grow);-ms-flex-negative: var(--flex-shrink);flex-shrink: var(--flex-shrink);-webkit-box-ordinal-group: var(--order);-ms-flex-order: var(--order);order: var(--order);-ms-flex-item-align: var(--align-self);align-self: var(--align-self)}:root{--page-title-display: block}.elementor-section{position: relative}.elementor-section .elementor-container{display: -webkit-box;display: -ms-flexbox;display: flex;margin-right: auto;margin-left: auto;position: relative}@media (max-width:1024px){.elementor-section .elementor-container{-ms-flex-wrap: wrap;flex-wrap: wrap}}.elementor-section.elementor-section-boxed>.elementor-container{max-width: 1140px}.elementor-row{width: 100%;display: -webkit-box;display: -ms-flexbox;display: flex}@media (max-width:1024px){.elementor-row{-ms-flex-wrap: wrap;flex-wrap: wrap}}.elementor-widget-wrap{position: relative;width: 100%;-ms-flex-wrap: wrap;flex-wrap: wrap;-ms-flex-line-pack: start;align-content: flex-start}.elementor:not(.elementor-bc-flex-widget) .elementor-widget-wrap{display: -webkit-box;display: -ms-flexbox;display: flex}.elementor-widget-wrap>.elementor-element{width: 100%}.elementor-widget{position: relative}.elementor-widget:not(:last-child){margin-bottom: 20px}.elementor-column{min-height: 1px}.elementor-column,.elementor-column-wrap{position: relative;display: -webkit-box;display: -ms-flexbox;display: flex}.elementor-column-wrap{width: 100%}@media (min-width:768px){.elementor-column.elementor-col-33{width: 33.333%}.elementor-column.elementor-col-50{width: 50%}.elementor-column.elementor-col-100{width: 100%}}@media (max-width:767px){.elementor-column{width: 100%}}.elementor-kit-3537{--e-global-color-primary: #6EC1E4;--e-global-color-secondary: #54595F;--e-global-color-text: #7A7A7A;--e-global-color-accent: #61CE70;--e-global-color-21d3b86d: #4054B2;--e-global-color-4e4079e4: #23A455;--e-global-color-2c647b98: #000;--e-global-color-6323191a: #FFF;--e-global-typography-primary-font-family: "Roboto";--e-global-typography-primary-font-weight: 600;--e-global-typography-secondary-font-family: "Roboto Slab";--e-global-typography-secondary-font-weight: 400;--e-global-typography-text-font-family: "Roboto";--e-global-typography-text-font-weight: 400;--e-global-typography-accent-font-family: "Roboto";--e-global-typography-accent-font-weight: 500}.elementor-section.elementor-section-boxed>.elementor-container{max-width: 1140px}.elementor-widget:not(:last-child){margin-bottom: 20px}@media (max-width:1024px){.elementor-section.elementor-section-boxed>.elementor-container{max-width: 1024px}}@media (max-width:767px){.elementor-section.elementor-section-boxed>.elementor-container{max-width: 767px}}.elementor-widget-heading .elementor-heading-title{color: var(--e-global-color-primary)}.elementor-widget-text-editor{color: var(--e-global-color-text)}.elementor-1256 .elementor-element.elementor-element-c94a9dc>.elementor-element-populated{margin: -30px 0 0 0;--e-column-margin-right: 0px;--e-column-margin-left: 0px}.elementor-1256 .elementor-element.elementor-element-c94a9dc>.elementor-element-populated>.elementor-widget-wrap{padding: 0}.elementor-1256 .elementor-element.elementor-element-e5ac992:not(.elementor-motion-effects-element-type-background){background-color: rgba(208,240,239,.25)}.elementor-1256 .elementor-element.elementor-element-e5ac992{padding: 36px 36px 0 36px}.elementor-1256 .elementor-element.elementor-element-f1ef31a{text-align: center}.elementor-1256 .elementor-element.elementor-element-f1ef31a .elementor-heading-title{color: #5b687d}.elementor-1256 .elementor-element.elementor-element-88a68ce{text-align: center}.elementor-1256 .elementor-element.elementor-element-88a68ce .elementor-heading-title{color: #14b6b1}.elementor-1256 .elementor-element.elementor-element-cb60859{text-align: justify}.elementor-1256 .elementor-element.elementor-element-cb60859>.elementor-widget-container{margin: 0 10% 0 10%;padding: 0 10% 0 10%}.elementor-1256 .elementor-element.elementor-element-247672d:not(.elementor-motion-effects-element-type-background){background-color: rgba(208,240,239,.25)}.elementor-1256 .elementor-element.elementor-element-247672d{margin-top: 0;margin-bottom: 36px;padding: 36px 36px 36px 36px}.elementor-1256 .elementor-element.elementor-element-254c7b0{text-align: left}.elementor-1256 .elementor-element.elementor-element-254c7b0>.elementor-widget-container{margin: 0}.elementor-1256 .elementor-element.elementor-element-fd19943{text-align: center}.elementor-1256 .elementor-element.elementor-element-fd19943 .elementor-heading-title{color: #fff}.elementor-1256 .elementor-element.elementor-element-fd19943>.elementor-widget-container{margin: -73px 0 0 0;padding: 17px 17px 17px 17px;background-color: rgba(19,0,110,.6)}.elementor-1256 .elementor-element.elementor-element-b35da22{text-align: justify}.elementor-1256 .elementor-element.elementor-element-b35da22>.elementor-widget-container{margin: -24px 0 0 0;padding: 0 5px 0 10px}.elementor-1256 .elementor-element.elementor-element-3a0efd8{text-align: left}.elementor-1256 .elementor-element.elementor-element-3a0efd8>.elementor-widget-container{margin: 0}.elementor-1256 .elementor-element.elementor-element-8392b7b{text-align: center}.elementor-1256 .elementor-element.elementor-element-8392b7b .elementor-heading-title{color: #fff}.elementor-1256 .elementor-element.elementor-element-8392b7b>.elementor-widget-container{margin: -73px 0 0 0;padding: 17px 17px 17px 17px;background-color: rgba(19,0,110,.65)}.elementor-1256 .elementor-element.elementor-element-2a4e7b2{text-align: justify}.elementor-1256 .elementor-element.elementor-element-2a4e7b2>.elementor-widget-container{margin: -24px 0 0 0;padding: 0 15px 0 15px}.elementor-1256 .elementor-element.elementor-element-851902b{text-align: left}.elementor-1256 .elementor-element.elementor-element-851902b>.elementor-widget-container{margin: 0}.elementor-1256 .elementor-element.elementor-element-c02407d{text-align: center}.elementor-1256 .elementor-element.elementor-element-c02407d .elementor-heading-title{color: #fff}.elementor-1256 .elementor-element.elementor-element-c02407d>.elementor-widget-container{margin: -73px 0 0 0;padding: 17px 17px 17px 17px;background-color: rgba(19,0,110,.68)}.elementor-1256 .elementor-element.elementor-element-0e45646{text-align: justify}.elementor-1256 .elementor-element.elementor-element-0e45646>.elementor-widget-container{margin: -24px 0 0 0;padding: 0 15px 0 15px}.elementor-1256 .elementor-element.elementor-element-d4ab7fe{text-align: justify}.elementor-1256 .elementor-element.elementor-element-d4ab7fe>.elementor-widget-container{padding: 0 100px 0 100px}.elementor-1256 .elementor-element.elementor-element-9856d22{text-align: right}.elementor-1256 .elementor-element.elementor-element-9856d22>.elementor-widget-container{padding: 0 10px 0 0}.elementor-1256 .elementor-element.elementor-element-daaea9a{text-align: left}.elementor-1256 .elementor-element.elementor-element-daaea9a>.elementor-widget-container{padding: 0 0 0 10px}@media (max-width:767px){.elementor-1256 .elementor-element.elementor-element-e5ac992{padding: 0}.elementor-1256 .elementor-element.elementor-element-247672d{padding: 0}.elementor-1256 .elementor-element.elementor-element-d4ab7fe>.elementor-widget-container{padding: 0}}@font-face{font-family: 'Source Sans Pro';font-style: italic;font-weight: 300;src: url(//fonts.gstatic.com//s/sourcesanspro/v21/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZZMkidi18E.ttf) format('truetype')}@font-face{font-family: 'Source Sans Pro';font-style: italic;font-weight: 400;src: url(//fonts.gstatic.com//s/sourcesanspro/v21/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7psDc.ttf) format('truetype')}@font-face{font-family: 'Source Sans Pro';font-style: italic;font-weight: 700;src: url(//fonts.gstatic.com//s/sourcesanspro/v21/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZZclSdi18E.ttf) format('truetype')}@font-face{font-family: 'Source Sans Pro';font-style: normal;font-weight: 300;src: url(//fonts.gstatic.com//s/sourcesanspro/v21/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwmRdr.ttf) format('truetype')}@font-face{font-family: 'Source Sans Pro';font-style: normal;font-weight: 400;src: url(//fonts.gstatic.com//s/sourcesanspro/v21/6xK3dSBYKcSV-LCoeQqfX1RYOo3qNq7g.ttf) format('truetype')}@font-face{font-family: 'Source Sans Pro';font-style: normal;font-weight: 700;src: url(//fonts.gstatic.com//s/sourcesanspro/v21/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwmRdr.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: italic;font-weight: 100;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOiCnqEu92Fr1Mu51QrEzAdKg.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: italic;font-weight: 300;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOjCnqEu92Fr1Mu51TjASc6CsE.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: italic;font-weight: 400;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOkCnqEu92Fr1Mu51xIIzc.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: italic;font-weight: 500;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOjCnqEu92Fr1Mu51S7ACc6CsE.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: italic;font-weight: 700;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOjCnqEu92Fr1Mu51TzBic6CsE.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: italic;font-weight: 900;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOjCnqEu92Fr1Mu51TLBCc6CsE.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 100;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOkCnqEu92Fr1MmgVxIIzc.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 300;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmSU5fBBc9.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 400;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxP.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 500;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmEU9fBBc9.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 700;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmWUlfBBc9.ttf) format('truetype')}@font-face{font-family: 'Roboto';font-style: normal;font-weight: 900;src: url(https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmYUtfBBc9.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 100;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjojIWmb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 200;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjoDISmb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 300;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjo0oSmb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 400;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjojISmb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 500;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjovoSmb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 600;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjoUoOmb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 700;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjoa4Omb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 800;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjoDIOmb2Rm.ttf) format('truetype')}@font-face{font-family: 'Roboto Slab';font-style: normal;font-weight: 900;src: url(https://fonts.gstatic.com/s/robotoslab/v23/BngbUXZYTXPIvIBgJJSb6s3BzlRRfKOFbvjoJYOmb2Rm.ttf) format('truetype')}
		
	</style>





	<!-- You can use Open Graph tags to customize link previews.
	Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
	<meta property="og:url"           content="<?php echo get_permalink() ?>" />
	<meta property="og:type"          content="website" />
	<meta property="og:title"         content="<?php echo get_the_title(); ?>" />
	
		<?php wp_head(); ?>

</head>



<body <?php body_class(); ?> id="check">

	<div id="page" class="hfeed site">

		<header id="masthead" class="site-header" role="banner">

        	<div class="home-link">

            	<div class="logo">

                	<a href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" rel="home">

				<h1 class="site-title"><?php echo do_shortcode('[site_logo]'); ?></h1>

				

			</a>

                </div>

                <div class="top-right">

                	<div class="top-links">

                    	<ul>

                        	<li class="email"><a href="mailto:sarah@chemicaltranslator.com">sarah@chemicaltranslator.com</a></li>


                            <li><a href="https://www.linkedin.com/in/sarah-silva-translator/" target="_blank"><img src="<?php echo get_template_directory_uri(); ?>/images/icon-ln.png" alt=""/></a></li>

                            <li><a href="https://www.xing.com/profile/Sarah_Silva?sc_o=mxb_p"  target="_blank"><img src="<?php echo get_template_directory_uri(); ?>/images/icon-xg.png" alt=""/></a></li>

                        </ul>

                    </div>

                	<div id="navbar" class="navbar">

				<nav id="site-navigation" class="navigation main-navigation" role="navigation">

					<button class="menu-toggle"><?php _e( 'Menu', 'twentythirteen' ); ?></button>

					<a class="screen-reader-text skip-link" href="#content" title="<?php esc_attr_e( 'Skip to content', 'twentythirteen' ); ?>"><?php _e( 'Skip to content', 'twentythirteen' ); ?></a>

					<?php wp_nav_menu( array( 'theme_location' => 'primary', 'menu_class' => 'nav-menu' ) ); ?>

					

				</nav><!-- #site-navigation -->

			</div><!-- #navbar -->

                </div>

            <div class="banner"><?php //echo do_shortcode("[metaslider id=4]"); ?>
<?php dynamic_sidebar( 'sidebar-3' ); ?>

        </div>

            </div>

        

        

			



			

		</header><!-- #masthead -->



		<div id="main" class="site-main">